apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sm-common
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Su-HackZ/argocd-app-config.git
    targetRevision: HEAD
    path: sm-common
  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
