apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sm-storage
spec:
  project: default
  source:
    repoURL: https://github.com/Su-HackZ/argocd-app-config.git
    targetRevision: HEAD
    path: test
  destination: 
    server: https://kubernetes.default.svc
    automated:
      selfHeal: true
      prune: true
