apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sm-storage
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: sm-storage
    repoURL: 'https://github.com/Su-HackZ/argocd-app-config.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true