---
# Source: sm-common/templates/staging-ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sm-sm-common-staging
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: sm-common
    component: staging
spec:
  rules:
  - host: ingress.local
    http:
      paths:
      - backend:
          serviceName: nginx-ingress-default-backend
          servicePort: 80